// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mocks/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/ilushka-off/go-musthave-metrics-tpl/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AllCounters mocks base method.
func (m *MockStorage) AllCounters() map[string]int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCounters")
	ret0, _ := ret[0].(map[string]int64)
	return ret0
}

// AllCounters indicates an expected call of AllCounters.
func (mr *MockStorageMockRecorder) AllCounters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCounters", reflect.TypeOf((*MockStorage)(nil).AllCounters))
}

// AllGauges mocks base method.
func (m *MockStorage) AllGauges() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllGauges")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// AllGauges indicates an expected call of AllGauges.
func (mr *MockStorageMockRecorder) AllGauges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllGauges", reflect.TypeOf((*MockStorage)(nil).AllGauges))
}

// Counter mocks base method.
func (m *MockStorage) Counter(name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counter", name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Counter indicates an expected call of Counter.
func (mr *MockStorageMockRecorder) Counter(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counter", reflect.TypeOf((*MockStorage)(nil).Counter), name)
}

// Gauge mocks base method.
func (m *MockStorage) Gauge(name string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gauge", name)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gauge indicates an expected call of Gauge.
func (mr *MockStorageMockRecorder) Gauge(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockStorage)(nil).Gauge), name)
}

// UpdateBatch mocks base method.
func (m *MockStorage) UpdateBatch(metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatch", metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatch indicates an expected call of UpdateBatch.
func (mr *MockStorageMockRecorder) UpdateBatch(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatch", reflect.TypeOf((*MockStorage)(nil).UpdateBatch), metrics)
}

// UpdateCounter mocks base method.
func (m *MockStorage) UpdateCounter(name string, value int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockStorageMockRecorder) UpdateCounter(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockStorage)(nil).UpdateCounter), name, value)
}

// UpdateGauge mocks base method.
func (m *MockStorage) UpdateGauge(name string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGauge", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockStorageMockRecorder) UpdateGauge(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockStorage)(nil).UpdateGauge), name, value)
}
