// Code generated by cmd/reset. DO NOT EDIT.

package fixture

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil {
		if resetter, ok := interface{}(r.child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}

func (w *WithEmbedded) Reset() {
	if w == nil {
		return
	}

	if resetter, ok := interface{}(&w.ResetableStruct).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	w.Extra = false
}
