// Package pool provides a generic, type-safe wrapper around sync.Pool for
// objects that know how to reset themselves (see cmd/reset).
package pool

import "sync"

// Resetter is implemented by types that can restore themselves to their
// initial state. Methods generated by cmd/reset have a pointer receiver, so
// the pool is normally instantiated with a pointer type, e.g. Pool[*MyStruct].
type Resetter interface {
	Reset()
}

// Pool is a container of reusable objects of a single type T.
type Pool[T Resetter] struct {
	p sync.Pool
}

// New creates a Pool. newFn is called to create a fresh object whenever the
// pool has none to hand out.
func New[T Resetter](newFn func() T) *Pool[T] {
	return &Pool[T]{
		p: sync.Pool{
			New: func() any { return newFn() },
		},
	}
}

// Get returns an object from the pool, or a new one if the pool is empty.
func (p *Pool[T]) Get() T {
	return p.p.Get().(T)
}

// Put resets x and returns it to the pool. The caller must not use x after
// calling Put.
func (p *Pool[T]) Put(x T) {
	x.Reset()
	p.p.Put(x)
}
